apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: buildpack-renku-build
spec:
  source:
    type: Git
    git: 
      url: https://github.com/Panaetius/emptyrepo.git
  paramValues:
    - name: dependencies
      value: |
        torch
        numpy
        pandas
        jupyter
    - name: procfile
      value: |
        web_renkulab: jupyter lab --no-browser --ip=0.0.0.0 --NotebookApp.token="" --NotebookApp.password="" --NotebookApp.base_url=$RENKU_BASE_URL_PATH
        web: jupyter lab --no-browser --ip=0.0.0.0 --NotebookApp.token="" --NotebookApp.password=""
        bash: bash
  strategy:
    name: buildpacks-v3-renku-python
    kind: ClusterBuildStrategy
  output:
    image: docker.io/renku/test-shipwright-python:latest
    pushSecret: renku-dockerhub-credentials
