description="a test builder for use with renkulab.io"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.10.1"
  version = "5.10.1"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/python:2.22.2"
  version = "2.22.2"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/source-removal:0.2.20"
  version = "0.2.20"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/environment-variables:4.7.3"
  version = "4.7.3"

[lifecycle]
  version = "0.20.4"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/python"
    version = "2.22.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.10.1"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "0.2.20"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    version = "4.7.3"


[stack]
  id = "io.buildpacks.stacks.jammy"
  build-image = "docker.io/paketobuildpacks/build-jammy-base:0.1.133"
  run-image = "docker.io/panaetius123/buildpack-base:latest4"
  run-image-mirrors = []
